
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author 76905
 */
public class ClientesP extends javax.swing.JPanel {

    DefaultTableModel modelo = new DefaultTableModel();
    
    public ClientesP() {
        initComponents();
        modelo=(DefaultTableModel)tablaC.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nomCliente = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        numTel = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Noto Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 150, 150));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Clientes");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        tablaC.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaC);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 150, 150));
        jLabel2.setText("Nombre del Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel2, gridBagConstraints);

        nomCliente.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        nomCliente.setPreferredSize(new java.awt.Dimension(150, 30));
        nomCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomClienteKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(nomCliente, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 150, 150));
        jLabel3.setText("Número Telefónico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jLabel3, gridBagConstraints);

        numTel.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        numTel.setPreferredSize(new java.awt.Dimension(150, 30));
        numTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numTelKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(numTel, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(78, 150, 150));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 10, 10);
        jPanel2.add(jButton1, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(!nomCliente.getText().isEmpty() || !numTel.getText().isEmpty()){
            if(numTel.getText().length() == 10){
                String id = generarID(nomCliente.getText(), numTel.getText());
                modelo.addRow(new Object[]{id, nomCliente.getText(), numTel.getText()});
                nomCliente.setText("");
                numTel.setText("");
            }
            else
                javax.swing.JOptionPane.showMessageDialog(null, "El número telefónico debe ser de 10 dígitos", "Error",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomClienteKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.letrasMayus(letra) && !Cake.letrasMinus(letra)){
            evt.consume();
        }
        
        if(Cake.tamaño(nomCliente.getText(), 20)){
            evt.consume();
        }
    }//GEN-LAST:event_nomClienteKeyTyped

    private void numTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numTelKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.numeros(letra)){
            evt.consume();
        }
        
        if(Cake.tamaño(numTel.getText(), 10)){
            evt.consume();
        }
    }//GEN-LAST:event_numTelKeyTyped

    public String generarID(String nombre, String telefono){
        String id = "";
        java.util.Random random = new java.util.Random();
        String nombreP = nombre.substring(0, 2).toUpperCase();
        char caracterNP = nombre.toUpperCase().charAt(random.nextInt(nombre.length()));
        char caracterTP1 = telefono.charAt(random.nextInt(telefono.length()));
        char caracterTP2 = telefono.charAt(random.nextInt(telefono.length()));
        String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        char caracterAl1 = caracteres.charAt(random.nextInt(caracteres.length()));
        char caracterAl2 = caracteres.charAt(random.nextInt(caracteres.length()));
        id = id + nombreP + caracterTP1 +  caracterTP2 + caracterNP + caracterAl1 + caracterAl2;
        
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField nomCliente;
    private javax.swing.JFormattedTextField numTel;
    private javax.swing.JTable tablaC;
    // End of variables declaration//GEN-END:variables
}
