
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author mayra
 */
public class ComprasP extends javax.swing.JPanel {

    String id_compra = "";
    ConexionBD conect = new ConexionBD();

    DefaultTableModel modeloCom = new DefaultTableModel();
    DefaultTableModel modeloProdCom = new DefaultTableModel();
    DefaultTableModel modeloProd = new DefaultTableModel();

    boolean ins = true;

    // Proveedor
    private java.util.ArrayList<Integer> proveedorIds = new java.util.ArrayList<>();

    /**
     * Creates new form ComprasP
     */
    public ComprasP() {
        initComponents();
        modeloCom = (DefaultTableModel)tablaCompras.getModel();
        modeloProdCom = (DefaultTableModel)tablaProdCom.getModel();
        modeloProd = (DefaultTableModel)tablaProd.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        comDialog = new javax.swing.JDialog();
        panelRegCompra = new javax.swing.JPanel();
        jLabelProv = new javax.swing.JLabel();
        proveedorCombo = new javax.swing.JComboBox<>();
        nuevoProvBtn = new javax.swing.JButton();
        lblRfc = new javax.swing.JLabel();
        valRfc = new javax.swing.JLabel();
        lblFolio = new javax.swing.JLabel();
        folioF = new javax.swing.JFormattedTextField();
        lblFechaFact = new javax.swing.JLabel();
        fechaFactF = new javax.swing.JFormattedTextField();
        lblOrigen = new javax.swing.JLabel();
        origenF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        hechoB1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rasF = new javax.swing.JTextPane();
        prodComDialog = new javax.swing.JDialog();
        panelRegProdC = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaProd = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaProdCom = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        codP = new javax.swing.JFormattedTextField();
        jLabelCodBarras = new javax.swing.JLabel();
        codBarrasP = new javax.swing.JFormattedTextField();
        buscarP = new javax.swing.JButton();
        estadoP = new javax.swing.JLabel();
        jLabelConcepto = new javax.swing.JLabel();
        conceptoP = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cantP = new javax.swing.JFormattedTextField();
        jLabelUnidadCompra = new javax.swing.JLabel();
        unidadCompraP = new javax.swing.JComboBox<>();
        jLabelFactor = new javax.swing.JLabel();
        factorP = new javax.swing.JFormattedTextField();
        jLabelUnidadVenta = new javax.swing.JLabel();
        unidadVentaP = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        precP = new javax.swing.JFormattedTextField();
        ivaP = new javax.swing.JCheckBox();
        jLabelMargen = new javax.swing.JLabel();
        margenP = new javax.swing.JFormattedTextField();
        jLabelPVenta = new javax.swing.JLabel();
        pVentaP = new javax.swing.JFormattedTextField();
        agP = new javax.swing.JButton();
        acP = new javax.swing.JButton();
        elP = new javax.swing.JButton();
        heP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panelTotales = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalFactura = new javax.swing.JLabel();
        totalFacturaF = new javax.swing.JFormattedTextField();
        lblCuadre = new javax.swing.JLabel();
        guardarFacturaBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOrdenCompras = new javax.swing.JLabel();
        cmbOrdenCompras = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        agreCompra = new javax.swing.JButton();
        actCompra = new javax.swing.JButton();

        comDialog.setTitle("Compras");
        comDialog.setAlwaysOnTop(true);
        comDialog.setMinimumSize(new java.awt.Dimension(620, 600));
        comDialog.setModal(true);
        comDialog.setSize(new java.awt.Dimension(620, 600));
        comDialog.getContentPane().setLayout(new java.awt.CardLayout());

        panelRegCompra.setLayout(new java.awt.GridBagLayout());

        jLabelProv.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelProv.setForeground(new java.awt.Color(78, 150, 150));
        jLabelProv.setText("Proveedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 10);
        panelRegCompra.add(jLabelProv, gridBagConstraints);

        proveedorCombo.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        proveedorCombo.setPreferredSize(new java.awt.Dimension(250, 30));
        proveedorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorComboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 20);
        panelRegCompra.add(proveedorCombo, gridBagConstraints);

        nuevoProvBtn.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        nuevoProvBtn.setText("+ Nuevo");
        nuevoProvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoProvBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 20);
        panelRegCompra.add(nuevoProvBtn, gridBagConstraints);

        lblRfc.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        lblRfc.setForeground(new java.awt.Color(78, 150, 150));
        lblRfc.setText("RFC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        panelRegCompra.add(lblRfc, gridBagConstraints);

        valRfc.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        valRfc.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        panelRegCompra.add(valRfc, gridBagConstraints);

        lblFolio.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        lblFolio.setForeground(new java.awt.Color(78, 150, 150));
        lblFolio.setText("Folio / Nº remisión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        panelRegCompra.add(lblFolio, gridBagConstraints);

        folioF.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        folioF.setPreferredSize(new java.awt.Dimension(250, 30));
        folioF.setMinimumSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        panelRegCompra.add(folioF, gridBagConstraints);

        lblFechaFact.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        lblFechaFact.setForeground(new java.awt.Color(78, 150, 150));
        lblFechaFact.setText("Fecha factura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        panelRegCompra.add(lblFechaFact, gridBagConstraints);

        fechaFactF.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        fechaFactF.setPreferredSize(new java.awt.Dimension(250, 30));
        fechaFactF.setMinimumSize(new java.awt.Dimension(250, 30));
        fechaFactF.setToolTipText("dd/MM/yyyy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        panelRegCompra.add(fechaFactF, gridBagConstraints);

        lblOrigen.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        lblOrigen.setForeground(new java.awt.Color(78, 150, 150));
        lblOrigen.setText("Origen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        panelRegCompra.add(lblOrigen, gridBagConstraints);

        origenF.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        origenF.setPreferredSize(new java.awt.Dimension(250, 30));
        origenF.setMinimumSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        panelRegCompra.add(origenF, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 150, 150));
        jLabel4.setText("Descripcion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 10);
        panelRegCompra.add(jLabel4, gridBagConstraints);

        hechoB1.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        hechoB1.setBackground(new java.awt.Color(125, 255, 177));
        hechoB1.setIcon(SvgIcon.load("/icons/guardar.svg", SvgIcon.MEDIUM));
        hechoB1.setText("Continuar →");
        hechoB1.setPreferredSize(new java.awt.Dimension(100, 40));
        hechoB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hechoB1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelRegCompra.add(hechoB1, gridBagConstraints);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(342, 70));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(342, 70));

        rasF.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        rasF.setPreferredSize(new java.awt.Dimension(340, 50));
        rasF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rasFKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(rasF);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelRegCompra.add(jScrollPane2, gridBagConstraints);

        comDialog.getContentPane().add(panelRegCompra, "card2");

        comDialog.setLocationRelativeTo(null);

        prodComDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        prodComDialog.setTitle("Compras");
        prodComDialog.setAlwaysOnTop(true);
        prodComDialog.setMinimumSize(new java.awt.Dimension(800, 450));
        prodComDialog.setModal(true);
        prodComDialog.setPreferredSize(new java.awt.Dimension(1000, 500));
        prodComDialog.setSize(new java.awt.Dimension(1000, 500));
        prodComDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                prodComDialogWindowClosing(evt);
            }
        });
        prodComDialog.getContentPane().setLayout(new java.awt.CardLayout());

        panelRegProdC.setLayout(new java.awt.BorderLayout());

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane7.setMinimumSize(new java.awt.Dimension(550, 402));
        jScrollPane7.setOpaque(false);
        jScrollPane7.setPreferredSize(new java.awt.Dimension(550, 402));

        tablaProd.setFont(new java.awt.Font("Noto Serif", 0, 16)); // NOI18N
        tablaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProd.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProdMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tablaProd);

        panelRegProdC.add(jScrollPane7, java.awt.BorderLayout.WEST);

        tablaProdCom.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        tablaProdCom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Concepto", "Cant", "Unidad", "P.Unit", "IVA", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaProdCom);

        panelRegProdC.add(jScrollPane6, java.awt.BorderLayout.EAST);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel9.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(78, 150, 150));
        jLabel9.setText("Código:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabel9, gridBagConstraints);

        codP.setEditable(true);
        codP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        codP.setPreferredSize(new java.awt.Dimension(140, 30));
        codP.setMinimumSize(new java.awt.Dimension(140, 30));
        codP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codPKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(codP, gridBagConstraints);

        jLabelCodBarras.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelCodBarras.setForeground(new java.awt.Color(78, 150, 150));
        jLabelCodBarras.setText("Cód. barras:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabelCodBarras, gridBagConstraints);

        codBarrasP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        codBarrasP.setPreferredSize(new java.awt.Dimension(140, 30));
        codBarrasP.setMinimumSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(codBarrasP, gridBagConstraints);

        buscarP.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        buscarP.setText("Buscar");
        buscarP.setPreferredSize(new java.awt.Dimension(100, 30));
        buscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(buscarP, gridBagConstraints);

        estadoP.setFont(new java.awt.Font("Noto Serif", 1, 14)); // NOI18N
        estadoP.setForeground(new java.awt.Color(78, 150, 150));
        estadoP.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 10);
        jPanel5.add(estadoP, gridBagConstraints);

        jLabelConcepto.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelConcepto.setForeground(new java.awt.Color(78, 150, 150));
        jLabelConcepto.setText("Concepto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabelConcepto, gridBagConstraints);

        conceptoP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        conceptoP.setPreferredSize(new java.awt.Dimension(260, 30));
        conceptoP.setMinimumSize(new java.awt.Dimension(260, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 10);
        jPanel5.add(conceptoP, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(78, 150, 150));
        jLabel11.setText("Cantidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabel11, gridBagConstraints);

        cantP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        cantP.setPreferredSize(new java.awt.Dimension(140, 30));
        cantP.setMinimumSize(new java.awt.Dimension(140, 30));
        cantP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantPKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(cantP, gridBagConstraints);

        jLabelUnidadCompra.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelUnidadCompra.setForeground(new java.awt.Color(78, 150, 150));
        jLabelUnidadCompra.setText("Unidad compra:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(jLabelUnidadCompra, gridBagConstraints);

        unidadCompraP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        unidadCompraP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pieza","Caja","Bolsa","Bulto","Botella","Lata","Paquete","Bote","Barra","Vaso","Tetra Pak","kg"}));
        unidadCompraP.setPreferredSize(new java.awt.Dimension(140, 30));
        unidadCompraP.setMinimumSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 10);
        jPanel5.add(unidadCompraP, gridBagConstraints);

        jLabelFactor.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelFactor.setForeground(new java.awt.Color(78, 150, 150));
        jLabelFactor.setText("Factor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabelFactor, gridBagConstraints);

        factorP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        factorP.setPreferredSize(new java.awt.Dimension(140, 30));
        factorP.setMinimumSize(new java.awt.Dimension(140, 30));
        factorP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recalcularPVenta();
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(factorP, gridBagConstraints);

        jLabelUnidadVenta.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelUnidadVenta.setForeground(new java.awt.Color(78, 150, 150));
        jLabelUnidadVenta.setText("Unidad venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(jLabelUnidadVenta, gridBagConstraints);

        unidadVentaP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        unidadVentaP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pieza","Caja","Bolsa","Bulto","Botella","Lata","Paquete","Bote","Barra","Vaso","Tetra Pak","kg"}));
        unidadVentaP.setPreferredSize(new java.awt.Dimension(140, 30));
        unidadVentaP.setMinimumSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 10);
        jPanel5.add(unidadVentaP, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(78, 150, 150));
        jLabel12.setText("Precio adqurido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabel12, gridBagConstraints);

        precP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        precP.setPreferredSize(new java.awt.Dimension(140, 30));
        precP.setMinimumSize(new java.awt.Dimension(140, 30));
        precP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precPKeyTyped(evt);
            }
        });
        precP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recalcularPVenta();
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(precP, gridBagConstraints);

        ivaP.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        ivaP.setText("Lleva IVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(ivaP, gridBagConstraints);

        jLabelMargen.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelMargen.setForeground(new java.awt.Color(78, 150, 150));
        jLabelMargen.setText("Margen %:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 6, 6);
        jPanel5.add(jLabelMargen, gridBagConstraints);

        margenP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        margenP.setPreferredSize(new java.awt.Dimension(140, 30));
        margenP.setMinimumSize(new java.awt.Dimension(140, 30));
        margenP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recalcularPVenta();
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(margenP, gridBagConstraints);

        jLabelPVenta.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        jLabelPVenta.setForeground(new java.awt.Color(78, 150, 150));
        jLabelPVenta.setText("Precio venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel5.add(jLabelPVenta, gridBagConstraints);

        pVentaP.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        pVentaP.setPreferredSize(new java.awt.Dimension(140, 30));
        pVentaP.setMinimumSize(new java.awt.Dimension(140, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 10);
        jPanel5.add(pVentaP, gridBagConstraints);

        agP.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        agP.setBackground(new java.awt.Color(125, 255, 177));
        agP.setIcon(SvgIcon.load("/icons/add-task.svg", SvgIcon.MEDIUM));
        agP.setText("Agregar");
        agP.setPreferredSize(new java.awt.Dimension(125, 33));
        agP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 10, 6);
        jPanel5.add(agP, gridBagConstraints);

        acP.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        acP.setBackground(new java.awt.Color(255, 251, 128));
        acP.setIcon(SvgIcon.load("/icons/edit.svg", SvgIcon.MEDIUM));
        acP.setText("Actualizar");
        acP.setPreferredSize(new java.awt.Dimension(125, 33));
        acP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 10, 6);
        jPanel5.add(acP, gridBagConstraints);

        elP.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        elP.setBackground(new java.awt.Color(252, 149, 149));
        elP.setIcon(SvgIcon.load("/icons/delete.svg", SvgIcon.MEDIUM));
        elP.setText("Eliminar");
        elP.setPreferredSize(new java.awt.Dimension(125, 33));
        elP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 10, 6);
        jPanel5.add(elP, gridBagConstraints);

        heP.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        heP.setBackground(new java.awt.Color(125, 255, 177));
        heP.setIcon(SvgIcon.load("/icons/guardar.svg", SvgIcon.MEDIUM));
        heP.setText("Hecho");
        heP.setPreferredSize(new java.awt.Dimension(125, 33));
        heP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hePActionPerformed(evt);
            }
        });
        heP.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 10, 10);
        jPanel5.add(heP, gridBagConstraints);

        panelRegProdC.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 150, 150));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Productos Inventario");
        jPanel4.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Noto Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 150, 150));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Productos Comprados");
        jPanel4.add(jLabel2);

        panelRegProdC.add(jPanel4, java.awt.BorderLayout.NORTH);

        panelTotales.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 8));

        lblSubtotal.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(78, 150, 150));
        lblSubtotal.setText("Subtotal: $0.00");
        panelTotales.add(lblSubtotal);

        lblIva.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        lblIva.setForeground(new java.awt.Color(78, 150, 150));
        lblIva.setText("IVA 16%: $0.00");
        panelTotales.add(lblIva);

        lblTotal.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(78, 150, 150));
        lblTotal.setText("Total: $0.00");
        panelTotales.add(lblTotal);

        lblTotalFactura.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        lblTotalFactura.setForeground(new java.awt.Color(78, 150, 150));
        lblTotalFactura.setText("Total en factura:");
        panelTotales.add(lblTotalFactura);

        totalFacturaF.setFont(new java.awt.Font("Noto Serif", 0, 16)); // NOI18N
        totalFacturaF.setPreferredSize(new java.awt.Dimension(110, 28));
        totalFacturaF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalFacturaFKeyReleased(evt);
            }
        });
        panelTotales.add(totalFacturaF);

        lblCuadre.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        lblCuadre.setText(" ");
        panelTotales.add(lblCuadre);

        guardarFacturaBtn.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        guardarFacturaBtn.setBackground(new java.awt.Color(125, 255, 177));
        guardarFacturaBtn.setIcon(SvgIcon.load("/icons/guardar.svg", SvgIcon.MEDIUM));
        guardarFacturaBtn.setText("Guardar factura");
        guardarFacturaBtn.setPreferredSize(new java.awt.Dimension(170, 33));
        guardarFacturaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFacturaBtnActionPerformed(evt);
            }
        });
        panelTotales.add(guardarFacturaBtn);

        panelRegProdC.add(panelTotales, java.awt.BorderLayout.SOUTH);

        prodComDialog.getContentPane().add(panelRegProdC, "card3");

        prodComDialog.setLocationRelativeTo(null);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Noto Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 150, 150));
        jLabel3.setIcon(SvgIcon.load("/icons/compras.svg", SvgIcon.LARGE));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Compras");
        jLabel3.setPreferredSize(new java.awt.Dimension(163, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.CENTER;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        lblOrdenCompras.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        lblOrdenCompras.setText("Ordenar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 8, 10);
        jPanel1.add(lblOrdenCompras, gridBagConstraints);

        cmbOrdenCompras.setFont(new java.awt.Font("Noto Serif", 0, 16)); // NOI18N
        cmbOrdenCompras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Sin ordenar", "Más reciente", "Más antiguo", "Mayor monto", "Menor monto"}));
        cmbOrdenCompras.setPreferredSize(new java.awt.Dimension(200, 30));
        cmbOrdenCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrdenComprasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 8, 10);
        jPanel1.add(cmbOrdenCompras, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(540, 402));

        tablaCompras.setFont(new java.awt.Font("Noto Serif", 0, 14)); // NOI18N
        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compra", "Folio", "Proveedor", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCompras);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(150, 105));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        agreCompra.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        agreCompra.setBackground(new java.awt.Color(125, 255, 177));
        agreCompra.setIcon(SvgIcon.load("/icons/add-task.svg", SvgIcon.MEDIUM));
        agreCompra.setText("Agregar");
        agreCompra.setPreferredSize(new java.awt.Dimension(127, 33));
        agreCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreCompraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 30);
        jPanel3.add(agreCompra, gridBagConstraints);

        actCompra.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        actCompra.setBackground(new java.awt.Color(255, 251, 128));
        actCompra.setIcon(SvgIcon.load("/icons/edit.svg", SvgIcon.MEDIUM));
        actCompra.setText("Actualizar");
        actCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actCompraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 10, 30);
        jPanel3.add(actCompra, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void agreCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreCompraActionPerformed
        cargarProveedores();
        folioF.setText(""); fechaFactF.setText(""); origenF.setText(""); rasF.setText(""); valRfc.setText("");
        comDialog.setVisible(true);
    }//GEN-LAST:event_agreCompraActionPerformed

    private void proveedorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorComboActionPerformed
        int idx = proveedorCombo.getSelectedIndex();
        if (idx > 0 && idx <= proveedorIds.size()) {
            String[] fiscal = conect.obtenerDatosProveedor(proveedorIds.get(idx - 1));
            valRfc.setText(fiscal[0].isEmpty() ? "(sin RFC)" : fiscal[0]);
            valRfc.setToolTipText(fiscal[1]);
        } else {
            valRfc.setText("");
            valRfc.setToolTipText(null);
        }
    }//GEN-LAST:event_proveedorComboActionPerformed

    private void nuevoProvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoProvBtnActionPerformed
        Mise.JOption("Registre el proveedor en el módulo Proveedores y vuelva a abrir esta ventana.", "Nuevo proveedor", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_nuevoProvBtnActionPerformed

    private void actCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actCompraActionPerformed
        if(tablaCompras.getSelectedRow() != -1){
            id_compra = "" + tablaCompras.getValueAt(tablaCompras.getSelectedRow(), 0);
            mostrarTablaProd();
            mostrarTablaProdCom();
            actualizarTotalesUI();
            prodComDialog.setVisible(true);
        } else{
            Mise.JOption("Debe seleccionar la fila que desea actualizar", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_actCompraActionPerformed

    private void hechoB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hechoB1ActionPerformed
        int idProvSeleccionado = -1;
        int idx = proveedorCombo.getSelectedIndex();
        if (idx > 0 && idx <= proveedorIds.size()) idProvSeleccionado = proveedorIds.get(idx - 1);

        String folio = folioF.getText().trim();
        if (idProvSeleccionado > 0 && !folio.isEmpty() && conect.folioYaRegistrado(idProvSeleccionado, folio)) {
            int r = Mise.JOptionYesNo("Esta factura (folio " + folio + ") ya fue registrada para este proveedor.\n¿Registrarla de todos modos?", "Folio duplicado");
            if (r != 0) return;
        }

        String fechaSql = "";
        String fechaUi = fechaFactF.getText().trim();
        if (!fechaUi.isEmpty()) {
            try {
                java.text.SimpleDateFormat in = new java.text.SimpleDateFormat("dd/MM/yyyy");
                java.text.SimpleDateFormat out = new java.text.SimpleDateFormat("yyyy-MM-dd");
                in.setLenient(false);
                fechaSql = out.format(in.parse(fechaUi));
            } catch (java.text.ParseException ex) {
                Mise.JOption("Fecha de factura inválida (use dd/MM/yyyy).", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String descripcion = rasF.getText().trim();
        String[] campos = { Interfaz.idVendedor, descripcion, "0", folio, fechaSql, origenF.getText().trim() };
        id_compra = conect.insertarCompraConProveedor(campos, idProvSeleccionado);
        if (id_compra == null || id_compra.isEmpty()) return;

        mostrarTablaProd();
        mostrarTablaProdCom();
        totalFacturaF.setText("");
        lblCuadre.setText("");
        actualizarTotalesUI();
        comDialog.setVisible(false);
        prodComDialog.setVisible(true);
    }//GEN-LAST:event_hechoB1ActionPerformed

    private void codPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codPKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.letrasMayus(letra) && !Cake.numeros(letra) && !Cake.guionShort(letra)){
            evt.consume();
        }

        if(Cake.tamaño(codP.getText(), 20)){
            evt.consume();
        }
    }//GEN-LAST:event_codPKeyTyped

    private void cantPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantPKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.numeros(letra)){
            evt.consume();
        }

        if(Cake.tamaño(cantP.getText(), 10)){
            evt.consume();
        }
    }//GEN-LAST:event_cantPKeyTyped

    private void precPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precPKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.numeros(letra) && !Cake.inicioPunto(letra)){
            evt.consume();
        }
        
        if(!(precP.getText().isEmpty())){
            if(Cake.hayPuntos(precP.getText()) && letra=='.'){
                evt.consume();
            } else{
                if(Cake.punto(precP.getText(), letra)){
                    evt.consume();
                }
            }
        } else{
            if(Cake.inicioPunto(letra)){
                evt.consume();
            }
        }
        
        if(Cake.tamaño(precP.getText(), 10)){
            evt.consume();
        }
    }//GEN-LAST:event_precPKeyTyped

    private void agPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agPActionPerformed
        String codigo = codP.getText().trim();
        if (codigo.isEmpty() || precP.getText().trim().isEmpty() || cantP.getText().trim().isEmpty()) {
            Mise.JOption("Debe llenar código, cantidad y precio de compra.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String factorStr = factorP.getText().trim().isEmpty() ? "1" : factorP.getText().trim();
        double factor;
        try { factor = Double.parseDouble(factorStr); } catch (NumberFormatException e) { factor = 1; }
        if (factor <= 0) { Mise.JOption("El factor debe ser mayor a 0.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE); return; }

        String idProd = conect.resolverCodigo(codigo);
        boolean nuevo = (idProd == null);

        if (nuevo) {
            if (!codigo.matches("^[A-Za-z0-9_-]{3,50}$")) {
                Mise.JOption("El código interno debe ser 3-50 caracteres (letras, números, - o _).", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (conceptoP.getText().trim().isEmpty()) {
                Mise.JOption("Escriba el concepto/nombre del producto nuevo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            String cb = codBarrasP.getText().trim();
            if (!cb.isEmpty() && !cb.matches("^[0-9]{8,14}$")) {
                Mise.JOption("El código de barras debe tener entre 8 y 14 dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (conect.codigoBarrasDuplicado(cb, codigo)) {
                Mise.JOption("Ese código de barras ya está en otro producto.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            String pVenta = pVentaP.getText().trim().isEmpty() ? "0" : pVentaP.getText().trim();
            String[] d = { codigo, conceptoP.getText().trim(), cb,
                (String) unidadCompraP.getSelectedItem(), (String) unidadVentaP.getSelectedItem(),
                factorStr, ivaP.isSelected() ? "t" : "f", pVenta, pVenta, "0" };
            if (!conect.crearProductoDesdeCompra(d)) return;
            idProd = codigo;
        }

        String[] campos = { id_compra, idProd, precP.getText().trim(), cantP.getText().trim(), factorStr };
        conect.insertarProdCompra(campos, ins);
        ins = true;
        limpiarCapturaRenglon();
        mostrarTablaProdCom();
        actualizarTotalesUI();
    }//GEN-LAST:event_agPActionPerformed

    private void limpiarCapturaRenglon() {
        codP.setText(""); codBarrasP.setText(""); conceptoP.setText("");
        cantP.setText(""); precP.setText(""); factorP.setText(""); margenP.setText(""); pVentaP.setText("");
        ivaP.setSelected(false); estadoP.setText("");
        setCamposNuevo(true);
    }

    private double[] calcularTotales() {
        double subtotal = 0, iva = 0;
        java.sql.ResultSet rs = conect.query(
            "SELECT precio_total, COALESCE(lleva_iva,false) iva FROM compra_producto WHERE id_compra='" + id_compra + "';");
        try {
            while (rs.next()) {
                double imp = rs.getDouble("precio_total");
                subtotal += imp;
                if (rs.getBoolean("iva")) iva += imp * 0.16;
            }
        } catch (java.sql.SQLException e) { System.out.println("Error al calcular totales"); }
        return new double[]{ subtotal, iva, subtotal + iva };
    }

    private void actualizarTotalesUI() {
        double[] t = calcularTotales();
        lblSubtotal.setText(String.format(java.util.Locale.US, "Subtotal: $%.2f", t[0]));
        lblIva.setText(String.format(java.util.Locale.US, "IVA 16%%: $%.2f", t[1]));
        lblTotal.setText(String.format(java.util.Locale.US, "Total: $%.2f", t[2]));
        verificarCuadre(t[2]);
    }

    private void verificarCuadre(double totalCalc) {
        String txt = totalFacturaF.getText().trim();
        if (txt.isEmpty()) { lblCuadre.setText(""); return; }
        try {
            double totalFact = Double.parseDouble(txt);
            boolean cuadra = Math.abs(totalFact - totalCalc) <= 0.50;
            lblCuadre.setText(cuadra ? "✓ Cuadra" : "✗ No cuadra");
            lblCuadre.setForeground(cuadra ? new java.awt.Color(0,150,0) : java.awt.Color.RED);
        } catch (NumberFormatException e) { lblCuadre.setText(""); }
    }

    private void totalFacturaFKeyReleased(java.awt.event.KeyEvent evt) {
        verificarCuadre(calcularTotales()[2]);
    }

    private void guardarFacturaBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (modeloProdCom.getRowCount() == 0) {
            Mise.JOption("Agregue al menos un producto antes de guardar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        double[] t = calcularTotales();
        String txt = totalFacturaF.getText().trim();
        if (!txt.isEmpty()) {
            try {
                if (Math.abs(Double.parseDouble(txt) - t[2]) > 0.50) {
                    int r = Mise.JOptionYesNo("El total calculado ($" + String.format(java.util.Locale.US,"%.2f",t[2])
                        + ") no cuadra con el de la factura ($" + txt + ").\n¿Guardar de todos modos?", "Totales no cuadran");
                    if (r != 0) return;
                }
            } catch (NumberFormatException ignored) {}
        }
        conect.actualizarTotalesCompra(id_compra, t[0], t[1], t[2]);
        prodComDialog.setVisible(false);
        mostrarTablaCom();
    }

    private void setCamposNuevo(boolean nuevo) {
        conceptoP.setEditable(nuevo);
        unidadCompraP.setEnabled(nuevo);
        unidadVentaP.setEnabled(nuevo);
        factorP.setEditable(nuevo);
        ivaP.setEnabled(nuevo);
        margenP.setEditable(nuevo);
        pVentaP.setEditable(nuevo);
        estadoP.setText(nuevo ? "● Nuevo" : "Existente");
    }

    private void buscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPActionPerformed
        String codigo = codP.getText().trim();
        if (codigo.isEmpty()) codigo = codBarrasP.getText().trim();
        if (codigo.isEmpty()) { Mise.JOption("Escriba un código interno o de barras.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE); return; }

        String idProd = conect.resolverCodigo(codigo);
        if (idProd != null) {
            String[] p = conect.obtenerProductoParaCompra(idProd);
            codP.setText(idProd);
            conceptoP.setText(p[0]);
            codBarrasP.setText(p[1]);
            unidadCompraP.setSelectedItem(p[2]);
            unidadVentaP.setSelectedItem(p[3]);
            factorP.setText(p[4]);
            ivaP.setSelected("t".equals(p[5]));
            setCamposNuevo(false);
        } else {
            if (factorP.getText().trim().isEmpty()) factorP.setText("1");
            if (margenP.getText().trim().isEmpty()) margenP.setText("30");
            setCamposNuevo(true);
        }
    }//GEN-LAST:event_buscarPActionPerformed

    private void recalcularPVenta() {
        if (!pVentaP.isEditable()) return;
        try {
            double precio = Double.parseDouble(precP.getText().trim());
            double factor = Double.parseDouble(factorP.getText().trim());
            double margen = Double.parseDouble(margenP.getText().trim());
            if (factor <= 0) return;
            double costoUnit = precio / factor;
            double venta = costoUnit * (1 + margen / 100.0);
            pVentaP.setText(String.format(java.util.Locale.US, "%.2f", venta));
        } catch (NumberFormatException ignored) {}
    }

    private void acPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acPActionPerformed
        if (tablaProdCom.getSelectedRow() == -1) {
            Mise.JOption("Seleccione la fila de la tabla de Productos Comprados que desea actualizar", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        codP.setText("" + tablaProdCom.getValueAt(tablaProdCom.getSelectedRow(), 0));
        cantP.setText("" + tablaProdCom.getValueAt(tablaProdCom.getSelectedRow(), 2));
        precP.setText("" + tablaProdCom.getValueAt(tablaProdCom.getSelectedRow(), 4));
        buscarPActionPerformed(null);
        ins = false;
    }//GEN-LAST:event_acPActionPerformed

    private void elPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elPActionPerformed
        if(tablaProdCom.getSelectedRow() == -1){
            Mise.JOption("Seleccione la fila de la tabla de Productos Comprados que desea eliminar", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else{
            String[] campos = {id_compra, "" + tablaProdCom.getValueAt(tablaProdCom.getSelectedRow(), 0)};
            conect.eliminarProdCompra(campos);
            mostrarTablaProdCom();
            actualizarTotalesUI();
        }
    }//GEN-LAST:event_elPActionPerformed

    private void prodComDialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_prodComDialogWindowClosing
        if(modeloProdCom.getRowCount() == 0){
            int res = Mise.JOptionYesNo("No registró ningun producto, ¿seguro que desea cerrar esta ventana?"
                    + "\n(al realizar esta acción la compra no podrá guardarse)", "Cerrar ventana");
            if(res == 0){
                conect.eliminarCompra(id_compra);
                prodComDialog.dispose();
            }
        } else{
            prodComDialog.setVisible(false);
            mostrarTablaCom();
        }
    }//GEN-LAST:event_prodComDialogWindowClosing

    private void rasFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rasFKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.letrasMayus(letra) && !Cake.numeros(letra) && !Cake.letrasMinus(letra) && !(Cake.inicioEspacios(letra))){
            evt.consume();
        }

        if(!(rasF.getText().isEmpty())){
            if(Cake.espacios(rasF.getText(), letra)){
                evt.consume();
            }
        }
        else{
            if(Cake.inicioEspacios(letra)){
                evt.consume();
            }
        }

        if(Cake.tamaño(rasF.getText(), 100)){
            evt.consume();
        }
    }//GEN-LAST:event_rasFKeyTyped

    private void hePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hePActionPerformed
        prodComDialog.setVisible(false);
        rasF.setText("");
        mostrarTablaCom();
    }//GEN-LAST:event_hePActionPerformed

    private void tablaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProdMouseClicked
        codP.setText("" + tablaProd.getValueAt(tablaProd.getSelectedRow(), 0));
        buscarPActionPerformed(null);
    }//GEN-LAST:event_tablaProdMouseClicked

    private void cmbOrdenComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrdenComprasActionPerformed
        aplicarOrdenCompras();
    }//GEN-LAST:event_cmbOrdenComprasActionPerformed

    private void aplicarOrdenCompras() {
        String sel = (String) cmbOrdenCompras.getSelectedItem();
        if ("Sin ordenar".equals(sel)) {
            tablaCompras.setRowSorter(null);
            return;
        }
        javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter =
            new javax.swing.table.TableRowSorter<>(modeloCom);
        tablaCompras.setRowSorter(sorter);
        if ("Más reciente".equals(sel)) {
            sorter.setComparator(3, java.util.Comparator.comparing(Object::toString));
            sorter.setSortKeys(java.util.Arrays.asList(new javax.swing.RowSorter.SortKey(3, javax.swing.SortOrder.DESCENDING)));
        } else if ("Más antiguo".equals(sel)) {
            sorter.setComparator(3, java.util.Comparator.comparing(Object::toString));
            sorter.setSortKeys(java.util.Arrays.asList(new javax.swing.RowSorter.SortKey(3, javax.swing.SortOrder.ASCENDING)));
        } else if ("Mayor monto".equals(sel)) {
            sorter.setComparator(4, java.util.Comparator.comparingDouble(o -> {
                try { return Double.parseDouble(o.toString()); } catch (Exception e) { return 0.0; }
            }));
            sorter.setSortKeys(java.util.Arrays.asList(new javax.swing.RowSorter.SortKey(4, javax.swing.SortOrder.DESCENDING)));
        } else if ("Menor monto".equals(sel)) {
            sorter.setComparator(4, java.util.Comparator.comparingDouble(o -> {
                try { return Double.parseDouble(o.toString()); } catch (Exception e) { return 0.0; }
            }));
            sorter.setSortKeys(java.util.Arrays.asList(new javax.swing.RowSorter.SortKey(4, javax.swing.SortOrder.ASCENDING)));
        }
        sorter.sort();
    }

    public void cargarProveedores(){
        proveedorIds.clear();
        proveedorCombo.removeAllItems();
        proveedorCombo.addItem("-- Sin proveedor --");
        java.sql.ResultSet rs = conect.obtenerProveedores();
        if(rs != null){
            try{
                while(rs.next()){
                    proveedorIds.add(rs.getInt("id_proveedor"));
                    proveedorCombo.addItem(rs.getString("nombre"));
                }
            } catch(java.sql.SQLException e){
                System.out.println("Error al cargar proveedores");
            }
        }
    }

    public void mostrarTablaCom(){
        Mise.limpiarTabla(modeloCom);
        java.sql.ResultSet rs = conect.query(
            "SELECT c.id_compra, COALESCE(c.folio_proveedor,'') folio, COALESCE(pr.nombre,'') prov, "
          + "c.fecha_compra, c.monto FROM compras c LEFT JOIN proveedor pr ON pr.id_proveedor=c.id_proveedor "
          + "ORDER BY c.id_compra DESC;");
        try{
            while(rs.next()){
                modeloCom.addRow(new Object[]{ rs.getString("id_compra"), rs.getString("folio"),
                    rs.getString("prov"), rs.getDate("fecha_compra"), rs.getDouble("monto") });
            }
        } catch(java.sql.SQLException e){ System.out.println("Error al mostrar la tabla compras"); }
    }
    
    public void mostrarTablaProdCom(){
        Mise.limpiarTabla(modeloProdCom);
        java.sql.ResultSet rs = conect.query(
            "SELECT cp.id_producto, p.nombre, cp.cantidad, COALESCE(cp.unidad_compra,'') uc, "
          + "cp.precio_adquirido, COALESCE(cp.lleva_iva,false) iva, cp.precio_total "
          + "FROM compra_producto cp JOIN producto p ON p.id_producto = cp.id_producto "
          + "WHERE cp.id_compra='" + id_compra + "';");
        try{
            while(rs.next()){
                modeloProdCom.addRow(new Object[]{ rs.getString("id_producto"), rs.getString("nombre"),
                    rs.getInt("cantidad"), rs.getString("uc"), rs.getDouble("precio_adquirido"),
                    rs.getBoolean("iva") ? "Sí" : "No", rs.getDouble("precio_total") });
            }
        } catch(java.sql.SQLException e){
            System.out.println("Error al mostrar productos comprados");
        }
    }
    
    public void mostrarTablaProd(){
        Mise.limpiarTabla(modeloProd);
        java.sql.ResultSet rs = conect.query("SELECT * FROM producto ORDER BY id_producto");
        try{
            while(rs.next()){
                modeloProd.addRow(new Object[]{rs.getString("id_producto"), rs.getString("nombre")});
            }
        } catch(java.sql.SQLException e){
            System.out.println("Error al mostrar la tabla de productos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acP;
    private javax.swing.JButton actCompra;
    private javax.swing.JComboBox<String> cmbOrdenCompras;
    private javax.swing.JButton agP;
    private javax.swing.JButton agreCompra;
    private javax.swing.JButton buscarP;
    private javax.swing.JFormattedTextField cantP;
    private javax.swing.JFormattedTextField codBarrasP;
    private javax.swing.JFormattedTextField codP;
    private javax.swing.JDialog comDialog;
    private javax.swing.JFormattedTextField conceptoP;
    private javax.swing.JButton elP;
    private javax.swing.JLabel estadoP;
    private javax.swing.JFormattedTextField factorP;
    private javax.swing.JFormattedTextField fechaFactF;
    private javax.swing.JFormattedTextField folioF;
    private javax.swing.JButton guardarFacturaBtn;
    private javax.swing.JButton heP;
    private javax.swing.JButton hechoB1;
    private javax.swing.JCheckBox ivaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodBarras;
    private javax.swing.JLabel jLabelConcepto;
    private javax.swing.JLabel jLabelFactor;
    private javax.swing.JLabel jLabelMargen;
    private javax.swing.JLabel jLabelPVenta;
    private javax.swing.JLabel jLabelProv;
    private javax.swing.JLabel jLabelUnidadCompra;
    private javax.swing.JLabel jLabelUnidadVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblCuadre;
    private javax.swing.JLabel lblFechaFact;
    private javax.swing.JLabel lblFolio;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblOrdenCompras;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalFactura;
    private javax.swing.JFormattedTextField margenP;
    private javax.swing.JButton nuevoProvBtn;
    private javax.swing.JFormattedTextField origenF;
    private javax.swing.JPanel panelRegCompra;
    private javax.swing.JPanel panelRegProdC;
    private javax.swing.JPanel panelTotales;
    private javax.swing.JFormattedTextField precP;
    private javax.swing.JDialog prodComDialog;
    private javax.swing.JComboBox<String> proveedorCombo;
    private javax.swing.JFormattedTextField pVentaP;
    private javax.swing.JTextPane rasF;
    private javax.swing.JFormattedTextField totalFacturaF;
    private javax.swing.JComboBox<String> unidadCompraP;
    private javax.swing.JComboBox<String> unidadVentaP;
    private javax.swing.JLabel valRfc;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaProd;
    private javax.swing.JTable tablaProdCom;
    // End of variables declaration//GEN-END:variables
}
