
import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rodth
 */
public class Interfaz extends javax.swing.JFrame {

    Boolean admActivo = false;
    Boolean userActivo = false;
    
    //Paneles
    InventarioP invPanel = new InventarioP();
    VentasP ventPanel = new VentasP();
    AdministracionP docsPanel = new AdministracionP();
    ApartadosP apPanel = new ApartadosP();
    ClientesP cliPanel = new ClientesP();
    
    
    
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelPrin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaN = new javax.swing.JLabel();
        etiquetaC = new javax.swing.JLabel();
        usuarioF = new javax.swing.JFormattedTextField();
        contraF = new javax.swing.JPasswordField();
        veriB = new javax.swing.JButton();
        eyeB = new javax.swing.JToggleButton();
        closeS = new javax.swing.JButton();
        inifinish = new javax.swing.JToggleButton();
        botones = new javax.swing.JPanel();
        boton0 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de Ventas");
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setSize(new java.awt.Dimension(1100, 700));

        panelPrin.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuariu.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 50, 10);
        panelPrin.add(jLabel1, gridBagConstraints);

        etiquetaN.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        etiquetaN.setForeground(new java.awt.Color(78, 150, 150));
        etiquetaN.setText("Nombre de Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrin.add(etiquetaN, gridBagConstraints);

        etiquetaC.setFont(new java.awt.Font("Noto Serif", 1, 18)); // NOI18N
        etiquetaC.setForeground(new java.awt.Color(78, 150, 150));
        etiquetaC.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrin.add(etiquetaC, gridBagConstraints);

        usuarioF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usuarioF.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        usuarioF.setPreferredSize(new java.awt.Dimension(180, 30));
        usuarioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFActionPerformed(evt);
            }
        });
        usuarioF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usuarioFKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        panelPrin.add(usuarioF, gridBagConstraints);

        contraF.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        contraF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraF.setPreferredSize(new java.awt.Dimension(180, 30));
        contraF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraFKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        panelPrin.add(contraF, gridBagConstraints);

        veriB.setFont(new java.awt.Font("Noto Serif", 1, 20)); // NOI18N
        veriB.setForeground(new java.awt.Color(78, 150, 150));
        veriB.setText("Verificar");
        veriB.setPreferredSize(new java.awt.Dimension(120, 50));
        veriB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veriBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 10, 10);
        panelPrin.add(veriB, gridBagConstraints);

        eyeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye2.png"))); // NOI18N
        eyeB.setBorderPainted(false);
        eyeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        panelPrin.add(eyeB, gridBagConstraints);

        closeS.setFont(new java.awt.Font("Noto Serif", 1, 20)); // NOI18N
        closeS.setForeground(new java.awt.Color(78, 150, 150));
        closeS.setText("Cerrar Sesión");
        closeS.setPreferredSize(new java.awt.Dimension(190, 50));
        closeS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelPrin.add(closeS, gridBagConstraints);
        closeS.setVisible(false);

        inifinish.setFont(new java.awt.Font("Noto Serif", 1, 20)); // NOI18N
        inifinish.setForeground(new java.awt.Color(78, 150, 150));
        inifinish.setText("Iniciar día");
        inifinish.setPreferredSize(new java.awt.Dimension(190, 50));
        inifinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inifinishActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 10, 10, 10);
        panelPrin.add(inifinish, gridBagConstraints);
        inifinish.setVisible(false);

        getContentPane().add(panelPrin, java.awt.BorderLayout.CENTER);

        botones.setLayout(new java.awt.GridLayout(0, 1));

        boton0.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        boton0.setForeground(new java.awt.Color(78, 150, 150));
        boton0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jom.png"))); // NOI18N
        boton0.setText("Principal");
        boton0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        botones.add(boton0);

        boton1.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        boton1.setForeground(new java.awt.Color(78, 150, 150));
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inv.png"))); // NOI18N
        boton1.setText("Inventario");
        boton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        botones.add(boton1);

        boton2.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        boton2.setForeground(new java.awt.Color(78, 150, 150));
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventA.png"))); // NOI18N
        boton2.setText("Ventas");
        boton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        botones.add(boton2);

        boton3.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        boton3.setForeground(new java.awt.Color(78, 150, 150));
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carp.png"))); // NOI18N
        boton3.setText("Administración");
        boton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        botones.add(boton3);

        boton4.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        boton4.setForeground(new java.awt.Color(78, 150, 150));
        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doc.png"))); // NOI18N
        boton4.setText("Sistema de Apartados");
        boton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        botones.add(boton4);

        boton6.setFont(new java.awt.Font("Noto Serif", 1, 16)); // NOI18N
        boton6.setForeground(new java.awt.Color(78, 150, 150));
        boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        boton6.setText("Registro de Clientes");
        boton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        botones.add(boton6);

        getContentPane().add(botones, java.awt.BorderLayout.WEST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void veriBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veriBActionPerformed
        // TODO add your handling code here:
        String us = usuarioF.getText();
        String c = contraF.getText();
        if(!us.isEmpty() || !c.isEmpty()){
            if(AdministracionP.userC.containsKey(us)){
                if(!AdministracionP.userC.get(us).equals(c)){
                    javax.swing.JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                else{
                    javax.swing.JOptionPane.showMessageDialog(null, "¡Bienvenido, " + us +"!");
                    userActivo = true;
                    if(us.equals(AdministracionP.administrador)){
                        admActivo = true;
                    }
                    botonesU(true);
                }
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "Datos érroneos, intentelo de nuevo", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_veriBActionPerformed

    private void usuarioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        if(userActivo)
            visibilidad(0);
    }//GEN-LAST:event_boton0ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        if(userActivo)
            visibilidad(1);
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        if (inifinish.isSelected())
            visibilidad(2);
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        if(admActivo)
            visibilidad(3);
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        if(userActivo)
            visibilidad(4);
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        if(userActivo)
            visibilidad(5);
    }//GEN-LAST:event_boton6ActionPerformed

    private void eyeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeBActionPerformed
        if(eyeB.isSelected()){
            contraF.setEchoChar((char)0);
            eyeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye1.png")));
        }
        else{
            contraF.setEchoChar('*');
            eyeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eye2.png")));
        }
    }//GEN-LAST:event_eyeBActionPerformed

    private void closeSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeSActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, "¡Hasta luego!");
        userActivo = false;
        admActivo = false;
        usuarioF.setText("");
        contraF.setText("");
        botonesU(false);
        
    }//GEN-LAST:event_closeSActionPerformed

    private void inifinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inifinishActionPerformed
        if(inifinish.isSelected()){
            javax.swing.JOptionPane.showMessageDialog(null, "Día inciado.");
            inifinish.setText("Terminar día");
            VentasP.diaV = 0;
            AdministracionP.contDei++;
        }
        else{
            AdministracionP.VentasDia.setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null, "Día terminado. Se han guardado las ventas del día");
            inifinish.setText("Ïniciar día");
            AdministracionP.regTVentas();
        }
    }//GEN-LAST:event_inifinishActionPerformed

    private void usuarioFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioFKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.letrasMinus(letra) && !Cake.letrasMayus(letra)){
            evt.consume();
        }

        if(Cake.tamaño(usuarioF.getText(), 10)){
            evt.consume();
        }
    }//GEN-LAST:event_usuarioFKeyTyped

    private void contraFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraFKeyTyped
        char letra = evt.getKeyChar();
        if(!Cake.numeros(letra)){
            evt.consume();
        }

        if(Cake.tamaño(contraF.getText(), 10)){
            evt.consume();
        }
    }//GEN-LAST:event_contraFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        
        try {
            UIManager.setLookAndFeel(new McWinLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    
    public void visibilidad(int a){
        panelPrin.setVisible(false);
        invPanel.setVisible(false);
        ventPanel.setVisible(false);
        docsPanel.setVisible(false);
        apPanel.setVisible(false);
        cliPanel.setVisible(false);
        switch(a){
            case 0://Panel Principal
                panelPrin.setVisible(true);
                break;
            case 1://Panel Inventario
                getContentPane().add(invPanel, java.awt.BorderLayout.CENTER);
                this.add(invPanel);
                if(admActivo){
                    InventarioP.panelBotones.setVisible(true);
                }
                else{
                    InventarioP.panelBotones.setVisible(false);
                }
                invPanel.setVisible(true);
                break;
            case 2://Panel Registro de Ventas
                getContentPane().add(ventPanel, java.awt.BorderLayout.CENTER);
                this.add(ventPanel);
                ventPanel.setVisible(true);
                break;
            case 3://Panel Administración
                getContentPane().add(docsPanel, java.awt.BorderLayout.CENTER);
                this.add(docsPanel);
                docsPanel.setVisible(true);
                break;
            case 4://Panel Sistema de Apartados
                getContentPane().add(apPanel, java.awt.BorderLayout.CENTER);
                this.add(apPanel);
                apPanel.setVisible(true);
                break;
            case 5://Panel Registro de Clientes
                getContentPane().add(cliPanel, java.awt.BorderLayout.CENTER);
                this.add(cliPanel);
                cliPanel.setVisible(true);
                break;
        }
    }
    
    public void botonesU(boolean x){
        closeS.setVisible(x);
        inifinish.setVisible(x);
        
        etiquetaN.setVisible(!x);
        etiquetaC.setVisible(!x);
        contraF.setVisible(!x);
        usuarioF.setVisible(!x);
        eyeB.setVisible(!x);
        veriB.setVisible(!x);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton6;
    private javax.swing.JPanel botones;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton closeS;
    private javax.swing.JPasswordField contraF;
    private javax.swing.JLabel etiquetaC;
    private javax.swing.JLabel etiquetaN;
    private javax.swing.JToggleButton eyeB;
    private javax.swing.JToggleButton inifinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrin;
    private javax.swing.JFormattedTextField usuarioF;
    private javax.swing.JButton veriB;
    // End of variables declaration//GEN-END:variables
}
