

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rodth
 */
public class Interfaz extends javax.swing.JFrame {

    InventarioP invPanel = new InventarioP();
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelPrin = new javax.swing.JPanel();
        panelT = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botones = new javax.swing.JPanel();
        homeB = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de Ventas");
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setSize(new java.awt.Dimension(1100, 700));

        panelPrin.setBackground(new java.awt.Color(246, 255, 246));

        javax.swing.GroupLayout panelPrinLayout = new javax.swing.GroupLayout(panelPrin);
        panelPrin.setLayout(panelPrinLayout);
        panelPrinLayout.setHorizontalGroup(
            panelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        panelPrinLayout.setVerticalGroup(
            panelPrinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrin, java.awt.BorderLayout.CENTER);

        panelT.setBackground(new java.awt.Color(114, 181, 164));
        panelT.setLayout(new java.awt.BorderLayout());

        titulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Punto de Ventas");
        panelT.add(titulo, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vM.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelT.add(jLabel1, java.awt.BorderLayout.LINE_START);

        getContentPane().add(panelT, java.awt.BorderLayout.PAGE_START);

        botones.setBackground(new java.awt.Color(213, 245, 213));
        botones.setLayout(new java.awt.GridLayout(0, 1));

        homeB.setBackground(new java.awt.Color(186, 235, 186));
        homeB.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        homeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/casita.png"))); // NOI18N
        homeB.setText("Principal");
        homeB.setBorder(null);
        homeB.setBorderPainted(false);
        homeB.setContentAreaFilled(false);
        homeB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBMouseExited(evt);
            }
        });
        homeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBActionPerformed(evt);
            }
        });
        botones.add(homeB);

        boton1.setBackground(new java.awt.Color(186, 235, 186));
        boton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inv.png"))); // NOI18N
        boton1.setText("Inventario  ");
        boton1.setBorder(null);
        boton1.setBorderPainted(false);
        boton1.setContentAreaFilled(false);
        boton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton1MouseExited(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        botones.add(boton1);

        boton2.setBackground(new java.awt.Color(186, 235, 186));
        boton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        boton2.setText("Registro de Ventas");
        boton2.setBorder(null);
        boton2.setBorderPainted(false);
        boton2.setContentAreaFilled(false);
        boton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton2MouseExited(evt);
            }
        });
        botones.add(boton2);

        boton3.setBackground(new java.awt.Color(186, 235, 186));
        boton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/docs.png"))); // NOI18N
        boton3.setText("Documentos");
        boton3.setBorder(null);
        boton3.setBorderPainted(false);
        boton3.setContentAreaFilled(false);
        boton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton3MouseExited(evt);
            }
        });
        botones.add(boton3);

        boton4.setBackground(new java.awt.Color(186, 235, 186));
        boton4.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apartao.png"))); // NOI18N
        boton4.setText("Sistema de Apartados   ");
        boton4.setBorder(null);
        boton4.setBorderPainted(false);
        boton4.setContentAreaFilled(false);
        boton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton4MouseExited(evt);
            }
        });
        botones.add(boton4);

        boton5.setBackground(new java.awt.Color(186, 235, 186));
        boton5.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        boton5.setText("Resgistro de Clientes");
        boton5.setBorder(null);
        boton5.setBorderPainted(false);
        boton5.setContentAreaFilled(false);
        boton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton5MouseExited(evt);
            }
        });
        botones.add(boton5);

        getContentPane().add(botones, java.awt.BorderLayout.WEST);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseEntered
        // TODO add your handling code here:
        boton5.requestFocus();
        boton5.setBackground(new java.awt.Color(220,249,220));
    }//GEN-LAST:event_boton5MouseEntered

    private void boton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseExited
        // TODO add your handling code here:
        boton5.setBackground(new java.awt.Color(186,235,186));
    }//GEN-LAST:event_boton5MouseExited

    private void homeBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBMouseEntered
        // TODO add your handling code here:
        homeB.requestFocus();
        homeB.setBackground(new java.awt.Color(220,249,220));
    }//GEN-LAST:event_homeBMouseEntered

    private void homeBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBMouseExited
        // TODO add your handling code here:
        homeB.setBackground(new java.awt.Color(186,235,186));
    }//GEN-LAST:event_homeBMouseExited

    private void boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseEntered
        // TODO add your handling code here:
        boton1.requestFocus();
        boton1.setBackground(new java.awt.Color(220,249,220));
    }//GEN-LAST:event_boton1MouseEntered

    private void boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseExited
        // TODO add your handling code here:
        boton1.setBackground(new java.awt.Color(186,235,186));
    }//GEN-LAST:event_boton1MouseExited

    private void boton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseEntered
        // TODO add your handling code here:
        boton2.requestFocus();
        boton2.setBackground(new java.awt.Color(220,249,220));
    }//GEN-LAST:event_boton2MouseEntered

    private void boton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseExited
        // TODO add your handling code here:
        boton2.setBackground(new java.awt.Color(186,235,186));
    }//GEN-LAST:event_boton2MouseExited

    private void boton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseEntered
        // TODO add your handling code here:
        boton3.requestFocus();
        boton3.setBackground(new java.awt.Color(220,249,220));
    }//GEN-LAST:event_boton3MouseEntered

    private void boton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseExited
        // TODO add your handling code here:
        boton3.setBackground(new java.awt.Color(186,235,186));
    }//GEN-LAST:event_boton3MouseExited

    private void boton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseEntered
        // TODO add your handling code here:
        boton4.requestFocus();
        boton4.setBackground(new java.awt.Color(220,249,220));
    }//GEN-LAST:event_boton4MouseEntered

    private void boton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseExited
        // TODO add your handling code here:
        boton4.setBackground(new java.awt.Color(186,235,186));
    }//GEN-LAST:event_boton4MouseExited

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
        getContentPane().add(invPanel, java.awt.BorderLayout.CENTER);
        this.add(invPanel);
    }//GEN-LAST:event_boton1ActionPerformed

    private void homeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBActionPerformed
        // TODO add your handling code here:
        System.out.print("Hola Mundo\n");
    }//GEN-LAST:event_homeBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JPanel botones;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton homeB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelPrin;
    private javax.swing.JPanel panelT;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
